import Header from "../../src/components/header"
import Footer from "../../src/components/footer"
import Head from "next/head"

export default function Main() {
  return (
    <div className="layout_basic">
      <Head>
        <title>點點簽</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="main">
        <h1>Hello!</h1>
      </main>
      <Footer step={"upload"} />
    </div>
  )
}
