import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import Header from "../src/components/header"
import logo from "../src/assets/img/logo.svg"

export default function Home() {
  return (
    <div className="layout_basic">
      <Head>
        <title>點點簽</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="main__home">
        <div>
          <div>
            <Image src={logo} alt="logo" />
            <p>線上簽署，方便快速。</p>
          </div>
          <Link href="/main">簽署新文件</Link>
        </div>
      </main>
    </div>
  )
}
