import Head from "next/head"
import Header from "../src/components/header"

export default function Home() {
  return (
    <div className="layout_basic">
      <Head>
        <title>點點簽</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  )
}
