import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import Header from "../src/components/header"
import logo from "../src/assets/img/logo.svg"

export default function Home() {
  return (
    <div className="layout_basic">
      <Head>
        <title>點點簽</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="home">
        <div className="home__cta">
          <div>
            <Image src={logo} alt="logo" />
            <h1 className="home__title">線上簽署，方便快速。</h1>
          </div>
          <Link href="/main" className="btn home__link">
            簽署新文件
          </Link>
        </div>
      </main>
    </div>
  )
}
